/**
 * Hippo.Web, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type JobStatus = 'Unknown' | 'Pending' | 'Running' | 'Dead';

export const JobStatus = {
    Unknown: 'Unknown' as JobStatus,
    Pending: 'Pending' as JobStatus,
    Running: 'Running' as JobStatus,
    Dead: 'Dead' as JobStatus
};

