/**
 * Hippo.Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type OperationType = 'Add' | 'Remove' | 'Replace' | 'Move' | 'Copy' | 'Test' | 'Invalid';

export const OperationType = {
    Add: 'Add' as OperationType,
    Remove: 'Remove' as OperationType,
    Replace: 'Replace' as OperationType,
    Move: 'Move' as OperationType,
    Copy: 'Copy' as OperationType,
    Test: 'Test' as OperationType,
    Invalid: 'Invalid' as OperationType
};

