name: Publish devcontainer image

on:
  push:
    tags:
    - "*"

jobs:
  release:
    name: Push devcontainer/codespaces image to GitHub Package Registry
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}-dev
          tags: |
            type=semver,pattern={{raw}},priority=1
            type=semver,pattern={{version}},priority=2
            type=semver,pattern={{major}}.{{minor}},priority=3
            type=sha,priority=4
          flavor: |
            latest=true

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          file: .devcontainer/Dockerfile
          context: .devcontainer
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
